package ch.epfl.dias.cs460.rel.early.volcano.late

import ch.epfl.dias.cs460.helpers.builder.skeleton
import ch.epfl.dias.cs460.helpers.rel.RelOperator.{LateTuple, NilLateTuple}

import scala.collection.mutable

/**
  * @inheritdoc
  *
  * @see [[ch.epfl.dias.cs460.helpers.builder.skeleton.Stitch]]
  * @see [[ch.epfl.dias.cs460.helpers.rel.late.volcano.naive.Operator]]
  */
class Stitch protected(
                              left: ch.epfl.dias.cs460.helpers.rel.late.volcano.naive.Operator,
                              right: ch.epfl.dias.cs460.helpers.rel.late.volcano.naive.Operator
                            ) extends skeleton.Stitch[
  ch.epfl.dias.cs460.helpers.rel.late.volcano.naive.Operator
](left, right)
  with ch.epfl.dias.cs460.helpers.rel.late.volcano.naive.Operator {

  /**
   * This is terrible practice because the VID type is defined somewhere else, but the provided skeleton
   * leaves us no choice.
   */
  private type VID = Long

  /**
   * Hash table for the tuples of the right operator.
   */
  private val rightHashMap = mutable.HashMap.empty[VID, Iterable[LateTuple]]

  /**
   * Each tuple from the left operator can generate multiple output tuples.
   * In order to iterate only once through the left operator, we store
   * all the output tuples generated by a "left" tuple in this
   * output buffer. Once it's empty, we fetch the next left tuple.
   */
  private val outputBuffer = mutable.Queue.empty[LateTuple]

  /**
    * @inheritdoc
    */
  override def open(): Unit =
    rightHashMap.clear()
    rightHashMap ++= right groupBy (_.vid)
    outputBuffer.clear()
    left.open()

  /**
    * @inheritdoc
    */
  override def next(): Option[LateTuple] =
    if outputBuffer.isEmpty then
      // Find the next left tuple that matches some right tuple
      val matchingTupleBuffers = LazyList continually left.next() takeWhile (_.isDefined) map (_.get) map {
        leftTuple =>
          rightHashMap get leftTuple.vid map {
            for rightTuple <- _
              yield LateTuple(leftTuple.vid, leftTuple.value ++ rightTuple.value)
          }
      } collect { case Some(outputTuples) => outputTuples }
      matchingTupleBuffers.headOption flatMap { matchingTuples =>
        // If there are matching tuples, fill the output buffer and recurse
        outputBuffer ++= matchingTuples
        next()
      }
    else
      Some(outputBuffer.dequeue())

  /**
    * @inheritdoc
    */
  override def close(): Unit =
    left.close()
    outputBuffer.clear()
    rightHashMap.clear()
}
